### ISSUE TITLE
What about binary payloads

### ISSUE THREAD

**Issue by codepr** [albertodeago/curl-generator#2]
The `getCurlBody` API currently generate only JSON payloads, what about `--data-binary` payloads or images? Nice work btw!

**Comment by albertodeago** [comment]
Seems legit, will work on it

**Comment by wilhelmklopp** [comment]
I would also be interested in this. 

Thanks for making curl-generator @albertodeago !

**Comment by Fabb111** [comment]
I created a PR for this: #11
